import React from 'react';
import {
  AccountCircle, AddCircle, AlarmOn, Apps, ArrowBack, ArrowDownward,
  ArrowForward, ArrowUpward, Attachment, Autorenew, Block, Bookmark,
  BookmarkBorder, BugReport, Build, Cancel, Check, CheckBox, CheckCircle,
  ChevronLeft, ChevronRight, Clear, Close, CloudDownload, CloudUpload,
  Code, ContentCopy, Create, Delete, Description, Done, DoneAll,
  Download, Edit, Email, Error, ErrorOutline, Event, ExitToApp,
  ExpandLess, ExpandMore, Favorite, FavoriteBorder, FilterList,
  Folder, FolderOpen, FormatBold, FormatItalic, FormatUnderlined,
  Forum, Help, HelpOutline, History, Home, Info, InfoOutlined,
  KeyboardArrowDown, KeyboardArrowLeft, KeyboardArrowRight, KeyboardArrowUp,
  Language, Link, List, Lock, LockOpen, Menu, MoreHoriz, MoreVert,
  Notifications, NotificationsActive, NotificationsNone, Person, PersonAdd,
  PersonOutline, Phone, PhotoCamera, Print, Refresh, Remove, RemoveCircle,
  Save, Search, Send, Settings, Share, ShoppingCart, Star, StarBorder,
  ThumbDown, ThumbUp, Timer, Translate, Visibility, VisibilityOff,
  VolumeOff, VolumeUp, Warning, WarningAmber, ZoomIn, ZoomOut
} from '@mui/icons-material';

export const muiIconMap: { [key: string]: React.ReactNode } = {
  AccountCircle: <AccountCircle />,
  AddCircle: <AddCircle />,
  AlarmOn: <AlarmOn />,
  Apps: <Apps />,
  ArrowBack: <ArrowBack />,
  ArrowDownward: <ArrowDownward />,
  ArrowForward: <ArrowForward />,
  ArrowUpward: <ArrowUpward />,
  Attachment: <Attachment />,
  Autorenew: <Autorenew />,
  Block: <Block />,
  Bookmark: <Bookmark />,
  BookmarkBorder: <BookmarkBorder />,
  BugReport: <BugReport />,
  Build: <Build />,
  Cancel: <Cancel />,
  Check: <Check />,
  CheckBox: <CheckBox />,
  CheckCircle: <CheckCircle />,
  ChevronLeft: <ChevronLeft />,
  ChevronRight: <ChevronRight />,
  Clear: <Clear />,
  Close: <Close />,
  CloudDownload: <CloudDownload />,
  CloudUpload: <CloudUpload />,
  Code: <Code />,
  ContentCopy: <ContentCopy />,
  Create: <Create />,
  Delete: <Delete />,
  Description: <Description />,
  Done: <Done />,
  DoneAll: <DoneAll />,
  Download: <Download />,
  Edit: <Edit />,
  Email: <Email />,
  Error: <Error />,
  ErrorOutline: <ErrorOutline />,
  Event: <Event />,
  ExitToApp: <ExitToApp />,
  ExpandLess: <ExpandLess />,
  ExpandMore: <ExpandMore />,
  Favorite: <Favorite />,
  FavoriteBorder: <FavoriteBorder />,
  FilterList: <FilterList />,
  Folder: <Folder />,
  FolderOpen: <FolderOpen />,
  FormatBold: <FormatBold />,
  FormatItalic: <FormatItalic />,
  FormatUnderlined: <FormatUnderlined />,
  Forum: <Forum />,
  Help: <Help />,
  HelpOutline: <HelpOutline />,
  History: <History />,
  Home: <Home />,
  Info: <Info />,
  InfoOutlined: <InfoOutlined />,
  KeyboardArrowDown: <KeyboardArrowDown />,
  KeyboardArrowLeft: <KeyboardArrowLeft />,
  KeyboardArrowRight: <KeyboardArrowRight />,
  KeyboardArrowUp: <KeyboardArrowUp />,
  Language: <Language />,
  Link: <Link />,
  List: <List />,
  Lock: <Lock />,
  LockOpen: <LockOpen />,
  Menu: <Menu />,
  MoreHoriz: <MoreHoriz />,
  MoreVert: <MoreVert />,
  Notifications: <Notifications />,
  NotificationsActive: <NotificationsActive />,
  NotificationsNone: <NotificationsNone />,
  Person: <Person />,
  PersonAdd: <PersonAdd />,
  PersonOutline: <PersonOutline />,
  Phone: <Phone />,
  PhotoCamera: <PhotoCamera />,
  Print: <Print />,
  Refresh: <Refresh />,
  Remove: <Remove />,
  RemoveCircle: <RemoveCircle />,
  Save: <Save />,
  Search: <Search />,
  Send: <Send />,
  Settings: <Settings />,
  Share: <Share />,
  ShoppingCart: <ShoppingCart />,
  Star: <Star />,
  StarBorder: <StarBorder />,
  ThumbDown: <ThumbDown />,
  ThumbUp: <ThumbUp />,
  Timer: <Timer />,
  Translate: <Translate />,
  Visibility: <Visibility />,
  VisibilityOff: <VisibilityOff />,
  VolumeOff: <VolumeOff />,
  VolumeUp: <VolumeUp />,
  Warning: <Warning />,
  WarningAmber: <WarningAmber />,
  ZoomIn: <ZoomIn />,
  ZoomOut: <ZoomOut />
};